### ISSUE TITLE
[Bug] Undescriptive error for faulty lang configuration

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#116]
When the singular/plural system isn't being used correctly, the following error is thrown.
The expected behaviour is that a descriptive error is shown: It should let the admin know how to fix configuration.

````
[19:39:53 ERROR]: Could not pass event PlayerBedEnterEvent to BetterSleeping3 v3.0.0
java.lang.NumberFormatException: For input string: "<time>"
at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_251]
at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_251]
at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_251]
at be.dezijwegel.bettersleeping.messaging.Messenger.composeMessage(Messenger.java:59) ~[?:?]
at be.dezijwegel.bettersleeping.messaging.Messenger.sendMessage(Messenger.java:105) ~[?:?]
at be.dezijwegel.bettersleeping.runnables.SleepersRunnable.playerEnterBed(SleepersRunnable.java:83) ~[?:?]
at be.dezijwegel.bettersleeping.events.handlers.BedEventHandler.onBedEnter(BedEventHandler.java:94) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor588.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-307]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-307]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-307]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-307]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:267) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.EntityHuman.sleep(EntityHuman.java:1363) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.EntityPlayer.sleep(EntityPlayer.java:1054) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.EntityPlayer.sleep(EntityPlayer.java:1048) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.BlockBed.interact(BlockBed.java:59) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IBlockData.interact(IBlockData.java:236) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:496) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1413) ~[?:git-Paper-307]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-307]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-307]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
````

**Comment by Nuytemans-Dieter** [comment]
Fixed in 0bb23d71868f52196f0e621628b0478f494985d8
