### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#190]
> Hello. I'm on Paper version git-Paper-274 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
> with BetterSleeping3 v3.0.4
> sometimes I get this error in console:
> [Server thread/ERROR]: Could not pass event TimeSetToDayEvent to BetterSleeping3 v3.0.4
> This is my last log file if you need: ~~https://mclo.gs/YvCqts9~~ (no longer available)

**Comment by Nuytemans-Dieter** [comment]
This has been an issue ever since I installed BetterSleeping
I did not use BetterSleeping before the first installation
I'm running Java 13, Paper version 325, BetterSleeping version 3.0.4
```
[03:02:23] [Server thread/ERROR]: Could not pass event TimeSetToDayEvent to BetterSleeping3 v3.0.4
java.lang.NullPointerException: null
	at be.dezijwegel.bettersleeping.messaging.Messenger.sendMessage(Messenger.java:216) ~[?:?]
	at be.dezijwegel.bettersleeping.events.handlers.BuffsHandler.onSetToDay(BuffsHandler.java:86) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor497.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-325]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-325]
	at be.dezijwegel.bettersleeping.runnables.SleepersRunnable.run(SleepersRunnable.java:209) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-325]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-325]
	at java.lang.Thread.run(Thread.java:830) [?:?]
```
