### ISSUE TITLE
Could not pass event PlayerBedEnterEvent

### ISSUE THREAD

**Issue by ardakaraosmanoglu** [Nuytemans-Dieter/BetterSleeping#200]
Minecraft Version: 1.16.5 / Paperspigot
BetterSleeps v1.5.0

```
[16:02:59 ERROR]: Could not pass event PlayerBedEnterEvent to BetterSleeps v1.5.0
java.lang.NullPointerException: null
at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_282]
at java.io.InputStreamReader.<init>(InputStreamReader.java:97) ~[?:1.8.0_282]
at manu.BetterSleaps.BetterSleaps.reloadBedLocations(BetterSleaps.java:159) ~[?:?]
at manu.BetterSleaps.Events.BedEvents.atBed(BedEvents.java:42) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-444]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-444]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-444]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-444]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:278) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.EntityPlayer.sleep(EntityPlayer.java:1134) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.EntityHuman.sleep(EntityHuman.java:1280) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.BlockBed.interact(BlockBed.java:64) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.BlockBase$BlockData.interact(BlockBase.java:585) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:515) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-444]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-444]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]


```

**Comment by Co2Noss** [comment]
Hi @ardakaraosmanoglu BetterSleeps is a different plugin that isn't related to this plugin at all. You'll want to contact them instead. 
https://github.com/Manuton04/BetterSleeps
