### ISSUE TITLE
Fix console stacktrace

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#201]
```
     
> [23:47:37 ERROR]: Could not pass event TimeSetToDayEvent to BetterSleeping3 v3.0.4
java.lang.NullPointerException: null
at be.dezijwegel.bettersleeping.events.handlers.BuffsHandler.giveEffects(BuffsHandler.java:126) ~[?:?]
at be.dezijwegel.bettersleeping.events.handlers.BuffsHandler.onSetToDay(BuffsHandler.java:92) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor350.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-443]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-443]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-443]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-443]
at be.dezijwegel.bettersleeping.runnables.SleepersRunnable.run(SleepersRunnable.java:209) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-443]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-443]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.5.jar:git-Paper-443]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-443]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-443]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-443]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-443]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Nuytemans-Dieter** [comment]
Dupe of #190
