### ISSUE TITLE
Fix backwards compatibility for 1.13, 1.14 and 1.15

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#219]
## BetterSleeping does not enable on older versions
This is due to a missing method in SnakeYAML. To fix this, we can either disable configuring `hooks.yml` for older servers, no longer allow recursive keys, move away from our `BetterYaml` library or update the `BetterYaml` library to support older versions.

```
[15:18:58] [Server thread/INFO]: [Multiverse-Core] Version 2.5.0-b727 (API v20) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
[15:18:58] [Server thread/INFO]: [BetterSleeping3] Enabling BetterSleeping3 v3.0.6
[15:18:58] [Server thread/INFO]: [BetterSleeping3] Detected Multiverse-Core. Delayed detection of worlds until Multiverse-Core loaded them into memory.
[15:18:58] [Server thread/INFO]: [BetterSleeping3] No missing options were found in config.yml!
[15:18:58] [Server thread/INFO]: [BetterSleeping3] No missing options were found in sleeping_settings.yml!
[15:18:58] [Server thread/ERROR]: Error occurred while enabling BetterSleeping3 v3.0.6 (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.LoaderOptions.setAllowRecursiveKeys(Z)V
	at be.dezijwegel.betteryaml.files.YamlReader.<init>(YamlReader.java:41) ~[?:?]
	at be.dezijwegel.betteryaml.files.YamlReader.<init>(YamlReader.java:27) ~[?:?]
	at be.dezijwegel.betteryaml.BetterYaml.<init>(BetterYaml.java:79) ~[?:?]
	at be.dezijwegel.betteryaml.BetterYaml.<init>(BetterYaml.java:36) ~[?:?]
	at be.dezijwegel.bettersleeping.BetterSleeping.startPlugin(BetterSleeping.java:126) ~[?:?]
	at be.dezijwegel.bettersleeping.BetterSleeping.onEnable(BetterSleeping.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[15:18:58] [Server thread/INFO]: [BetterSleeping3] Disabling BetterSleeping3 v3.0.6
[15:18:58] [Server thread/ERROR]: Error occurred while disabling BetterSleeping3 v3.0.6 (Is it up to date?)
java.lang.NullPointerException: null
	at be.dezijwegel.bettersleeping.BetterSleeping.disable(BetterSleeping.java:70) ~[?:?]
	at be.dezijwegel.bettersleeping.BetterSleeping.onDisable(BetterSleeping.java:64) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-391]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-391]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[15:18:58] 
```

**Comment by Nuytemans-Dieter** [comment]
Fixed by upgrading BetterYaml
