### ISSUE TITLE
Sometimes config reading causes startup errors

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#252]
**Describe the bug**

> So I keep getting this error on startup, plugin works fine without any changes but once I start making editing the config files the plugin basically breaks. I have tried rewriting the configs twice already, figured I'd let you know about it.

<details>
<summary>Startup logs</summary>

```
[02:14:16] [Server thread/INFO]: [BetterSleeping4] Enabling BetterSleeping4 v4.0.0
[02:14:17] [Server thread/WARN]: java.nio.file.AccessDeniedException: plugins/BetterSleeping4/config.yml
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2997)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3040)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:191)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:86)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.OptionalBetterYaml.<init>(OptionalBetterYaml.java:92)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer.<init>(ConfigContainer.java:70)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.GUICE$TRAMPOLINE(<generated>)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.apply(<generated>)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.startPlugin(BetterSleeping.java:84)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.onEnable(BetterSleeping.java:67)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:14:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:14:17] [Server thread/WARN]: java.nio.file.AccessDeniedException: plugins/BetterSleeping4/buffs.yml
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2997)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3040)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:191)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:86)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.OptionalBetterYaml.<init>(OptionalBetterYaml.java:92)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer.<init>(ConfigContainer.java:71)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.GUICE$TRAMPOLINE(<generated>)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.apply(<generated>)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.startPlugin(BetterSleeping.java:84)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.onEnable(BetterSleeping.java:67)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:14:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:14:17] [Server thread/WARN]: java.nio.file.AccessDeniedException: plugins/BetterSleeping4/bypassing.yml
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2997)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3040)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:191)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:86)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.OptionalBetterYaml.<init>(OptionalBetterYaml.java:92)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.OptionalBetterYaml.<init>(OptionalBetterYaml.java:72)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer.<init>(ConfigContainer.java:72)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.GUICE$TRAMPOLINE(<generated>)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.apply(<generated>)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.startPlugin(BetterSleeping.java:84)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.onEnable(BetterSleeping.java:67)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:14:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:14:17] [Server thread/WARN]: java.nio.file.AccessDeniedException: plugins/BetterSleeping4/hooks.yml
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2997)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3040)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:191)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:86)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.OptionalBetterYaml.<init>(OptionalBetterYaml.java:92)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer.<init>(ConfigContainer.java:73)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.GUICE$TRAMPOLINE(<generated>)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.apply(<generated>)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.startPlugin(BetterSleeping.java:84)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.onEnable(BetterSleeping.java:67)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:14:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:14:17] [Server thread/WARN]: java.nio.file.AccessDeniedException: plugins/BetterSleeping4/sleeping_settings.yml
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[02:14:17] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2997)
[02:14:17] [Server thread/WARN]: 	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3040)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:191)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.BetterYaml.<init>(BetterYaml.java:86)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.shade.betteryaml.OptionalBetterYaml.<init>(OptionalBetterYaml.java:92)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer.<init>(ConfigContainer.java:74)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.GUICE$TRAMPOLINE(<generated>)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.model.ConfigContainer$$FastClassByGuice$$4220012.apply(<generated>)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
[02:14:17] [Server thread/WARN]: 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.startPlugin(BetterSleeping.java:84)
[02:14:17] [Server thread/WARN]: 	at be.betterplugins.bettersleeping.BetterSleeping.onEnable(BetterSleeping.java:67)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[02:14:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[02:14:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:14:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:14:17] [Server thread/ERROR]: [BetterSleeping4] This is a BetterYaml issue.
[02:14:17] [Server thread/ERROR]: [BetterSleeping4] BetterSleeping cannot enable due to an error in your jar file, please contact the developer!
[02:14:17] [Server thread/INFO]: [BetterSleeping4] Disabling BetterSleeping4 v4.0.0
```

</details>

**Comment by Nuytemans-Dieter** [comment]
Nothing can be done about insufficient permissions, closing this issue
