### ISSUE TITLE
BS4 Does not enable on 1.18 without Essentials

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#268]
```
[01:48:57] [Server thread/INFO]: [BetterSleeping4] Enabling BetterSleeping4 v4.0.0
[01:48:58] [Server thread/ERROR]: Error occurred while enabling BetterSleeping4 v4.0.0 (Is it up to date?)
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: NoClassDefFoundError: com/earth2me/essentials/Essentials
  at HooksModule.provideEssentialsHook(HooksModule.java:19)
  at BypassChecker.<init>(BypassChecker.java:25)
      \_ for 2nd parameter
  at BypassChecker.class(BypassChecker.java:25)
  at SleepWorldManager.<init>(SleepWorldManager.java:32)
      \_ for 3rd parameter
  at SleepWorldManager.class(SleepWorldManager.java:32)
  at BetterSleepingModule.provideCommandHandler(BetterSleepingModule.java:92)
      \_ for 1st parameter
  at BetterSleepingModule.provideCommandHandler(BetterSleepingModule.java:92)
  while locating BPCommandHandler

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
BPCommandHandler:     "be.betterplugins.bettersleeping.shade.core.commands.BPCommandHandler"
BetterSleepingModule: "be.betterplugins.bettersleeping.guice.BetterSleepingModule"
BypassChecker:        "be.betterplugins.bettersleeping.model.BypassChecker"
HooksModule:          "be.betterplugins.bettersleeping.guice.HooksModule"
SleepWorldManager:    "be.betterplugins.bettersleeping.model.sleeping.SleepWorldManager"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[BetterSleeping.jar:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[BetterSleeping.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1138) ~[BetterSleeping.jar:?]
	at be.betterplugins.bettersleeping.BetterSleeping.startPlugin(BetterSleeping.java:90) ~[BetterSleeping.jar:?]
	at be.betterplugins.bettersleeping.BetterSleeping.onEnable(BetterSleeping.java:65) ~[BetterSleeping.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-rc3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-rc3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-rc3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:726) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Nuytemans-Dieter** [comment]
Cannot reproduce
