### ISSUE TITLE
An error in the console, the game requires more players than, in principle, there are on the server

### ISSUE THREAD

**Issue by JuraRusan** [Nuytemans-Dieter/BetterSleeping#307]
Hello, for some time after the update from 1.19.2 to 1.19.4, we had an error in the console, we thought it would disappear when switching to 1.20.1 But no, it still remained.

WARN:
```
[09:12:49 WARN]: [BetterSleeping4] Task #117 for BetterSleeping4 v4.0.2 generated an exception
java.lang.NullPointerException: Cannot invoke "be.betterplugins.bettersleeping.messaging.ScreenMessageSender.sendMessage(String)" because "sender" is null
        at be.betterplugins.bettersleeping.messaging.ScreenMessenger.sendMessage(ScreenMessenger.java:39) ~[BetterSleeping.jar:?]
        at be.betterplugins.bettersleeping.shade.core.messaging.messenger.Messenger.sendMessage(Messenger.java:202) ~[BetterSleeping.jar:?]
        at be.betterplugins.bettersleeping.runnables.SleepRunnable.run(SleepRunnable.java:222) ~[BetterSleeping.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
and ERROR:
```
[09:29:47 ERROR]: Could not pass event PlayerBedEnterEvent to BetterSleeping4 v4.0.2
java.lang.NullPointerException: Cannot invoke "be.betterplugins.bettersleeping.messaging.ScreenMessageSender.sendMessage(String)" because "sender" is null
        at be.betterplugins.bettersleeping.messaging.ScreenMessenger.sendMessage(ScreenMessenger.java:39) ~[BetterSleeping.jar:?]
        at be.betterplugins.bettersleeping.shade.core.messaging.messenger.Messenger.sendMessage(Messenger.java:202) ~[BetterSleeping.jar:?]
        at be.betterplugins.bettersleeping.runnables.SleepRunnable.addSleeper(SleepRunnable.java:88) ~[BetterSleeping.jar:?]
        at be.betterplugins.bettersleeping.model.sleeping.SleepWorldManager.addSleeper(SleepWorldManager.java:107) ~[BetterSleeping.jar:?]
        at be.betterplugins.bettersleeping.listeners.BedEventListener.onSleep(BedEventListener.java:124) ~[BetterSleeping.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor562.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-84]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-84]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-84]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:289) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.level.ServerPlayer.startSleepInBed(ServerPlayer.java:1425) ~[?:?]
        at net.minecraft.world.entity.player.Player.startSleepInBed(Player.java:1529) ~[?:?]
        at net.minecraft.world.level.block.BedBlock.use(BedBlock.java:113) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1177) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:582) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
There is one person on the server, but for the skip it requires 2.
![image](https://github.com/Nuytemans-Dieter/BetterSleeping/assets/76946109/fa76881e-9b52-4e97-9381-38cd92f12797)

Server jar: 
```
This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03) Previous version: git-Paper-538 (MC: 1.19.4)
```
Server plugins:
```
BKCommonLib, AdvancedBan, AntiPopup, BetterSleeping4, BungeeGuard, BungeeTabListPlus, BungeeTeleportManager, Chunky, Citizens, CitizensCMD, CMI, CMILib, CoreProtect, DeluxeMenus, DiscordSRV, DoorsReloaded, dtlTradersPlus, EasyCommandBlocker, emotecraft, EndBiomeFixer, FastAsyncWorldEdit, GSit, HeadDatabase, HuskSync, InvisibleItemFrames, LightCleaner, LuckPerms, Maintenance, MaintenanceAddon, MobFarmManager, nLogin, NoMobGriefing, PlaceholderAPI, Plan, PlayerParticles, ProtocolLib, Shopkeepers, SkinsRestorer, spark, TabTPS, Vault, VentureChat, voicechat, WorldEditSelectionVisualizer, XConomy
```

We have another server, there is a similar version, but some of the plugins do not match with this server, and there is no warning or error.

Server jar: 
```
This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03) Previous version: git-Paper-538 (MC: 1.19.4)
```
Server plugins:
```
BKCommonLib, AdvancedBan, AntiPopup, BetterSleeping4, BungeeGuard, BungeeTabListPlus, BungeeTeleportManager, CMI, CMILib, CoreProtect, DeluxeMenus, DiscordSRV, DoorsReloaded, EasyCommandBlocker, emotecraft, EndBiomeFixer, GSit, HuskSync, InvisibleItemFrames, LightCleaner, LuckPerms, Maintenance, MaintenanceAddon, MobFarmManager, nLogin, NoMobGriefing, PlaceholderAPI, Plan, PlayerParticles, ProtocolLib, SkinsRestorer, spark, TabTPS, Vault, VentureChat, voicechat, WorldEdit, WorldEditSelectionVisualizer
```

We assume that there may be a conflict with some kind of plugin, but we don’t really understand which one, and we didn’t dare to turn it off and check it in turn. But judging by the difference:
```
Chunky, Citizens, CitizensCMD, dtlTradersPlus, FastAsyncWorldEdit, HeadDatabase, Shopkeepers, XConomy
```
Chunky - what with him that without him the effect is the same, he disappears
FastAsyncWorldEdit - we also had the usual one WorldEdit, the effect is the same.

Remains only:
```
Citizens, CitizensCMD, dtlTradersPlus, HeadDatabase, Shopkeepers, XConomy
```

Perhaps a conflict with some kind of plugin, perhaps not, we did not understand much by mistake.

**Comment by criticalsool** [comment]
Same here on :
`Paper version git-Paper-484 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4445d23)`

Bukkit Plugins:
`ActionHealth, BetterSleeping4, Celeste, ChestSort, CoreProtect, DecentHolograms, DiscordSRV, Essentials, GSit, Multiverse-Core Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, PerWorldPlugins, Welcomer_Plus, WorldEdit, WorldGuard`

WARN : 
```
! [sam. 22:45:42 WARN  BetterSleeping4] Task #14 for BetterSleeping4 v4.0.2 generated an exception
java.lang.NullPointerException: Cannot invoke "be.betterplugins.bettersleeping.messaging.ScreenMessageSender.sendMessage(String)" because "sender" is null
    at BetterSleeping.jar//be.betterplugins.bettersleeping.messaging.ScreenMessenger.sendMessage(ScreenMessenger.java:39)
    at BetterSleeping.jar//be.betterplugins.bettersleeping.shade.core.messaging.messenger.Messenger.sendMessage(Messenger.java:202)
    at BetterSleeping.jar//be.betterplugins.bettersleeping.runnables.SleepRunnable.run(SleepRunnable.java:194)
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

ERROR :
```
- [sam. 22:48:14 ERROR Minecraft] Could not pass event PlayerBedEnterEvent to BetterSleeping4 v4.0.2
java.lang.NullPointerException: Cannot invoke "be.betterplugins.bettersleeping.messaging.ScreenMessageSender.sendMessage(String)" because "sender" is null
    at BetterSleeping.jar//be.betterplugins.bettersleeping.messaging.ScreenMessenger.sendMessage(ScreenMessenger.java:39)
    at BetterSleeping.jar//be.betterplugins.bettersleeping.shade.core.messaging.messenger.Messenger.sendMessage(Messenger.java:202)
    at BetterSleeping.jar//be.betterplugins.bettersleeping.runnables.SleepRunnable.addSleeper(SleepRunnable.java:88)
    at BetterSleeping.jar//be.betterplugins.bettersleeping.model.sleeping.SleepWorldManager.addSleeper(SleepWorldManager.java:107)
    at BetterSleeping.jar//be.betterplugins.bettersleeping.listeners.BedEventListener.onSleep(BedEventListener.java:124)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor288.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at PerWorldPlugins-1.5.3.jar//net.tonimatasdev.perworldplugins.api.PerWorldRegisteredListener.callEvent(PerWorldRegisteredListener.java:31)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:317)
    at net.minecraft.server.level.ServerPlayer.startSleepInBed(ServerPlayer.java:1433)
    at net.minecraft.world.entity.player.Player.startSleepInBed(Player.java:1555)
    at net.minecraft.world.level.block.BedBlock.use(BedBlock.java:123)
    at net.minecraft.world.leve
```
